//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public abstract class AbstractProject
    {
        public abstract double? calculateTotalCost();
        public abstract double? calculateTax();
        public abstract double? calculateProfit();
        public abstract double? calculateIncome();
        public abstract double? calculateCost();
        public abstract Int32? calculateDeadLine();
    }
}