//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AllProject : Project
    {
        [Display(Name = "Оценка заказчика")]
        [DataType(DataType.Text)]
        public string CustomerEvaluatate { get; set; }

        [Display(Name = "Качество проекта")]
        [DataType(DataType.Text)]
        public string Quality { get; set; }

        [Display(Name = "Итоговая сумма")]
        [DataType(DataType.Currency)]
        public Nullable<double> TotalSum { get; set; }

        [Display(Name = "Соответствие срокам")]
        [DataType(DataType.Text)]
        public string DeadlineAccording { get; set; }
    }
}
