//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Project = new HashSet<Project>();
        }
    
        public System.Guid Id { get; set; }

        [Display(Name = "Наименование заказа")]
        [DataType(DataType.Text)]
        public string OrderName { get; set; }

        [Display(Name = "Дата заказа")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOrder { get; set; }

        [Display(Name = "Сроки выполнения")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DeadLineProject { get; set; }

        [Display(Name = "Стоимость проекта")]
        [DataType(DataType.Currency)]
        public string CostProject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Project { get; set; }
    }
}
