//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableForDesigners : TableForEmployee
    {

        [Display(Name = "Шаблон дизайна")]
        [DataType(DataType.Text)]
        public string TemplateDesign { get; set; }

        [Display(Name = "Цветовая гамма")]
        [DataType(DataType.Text)]
        public string StatmentColor { get; set; }

        [Display(Name = "Примерные сроки")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PervisionTerm { get; set; }

        [Display(Name = "Дата изменений")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateWork { get; set; }
    }
}
