//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableForDeveloper : TableForEmployee
    {

        [Display(Name = "Дата разработки")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateDev { get; set; }

        [Display(Name = "Описание изменений")]
        [DataType(DataType.MultilineText)]
        public string StepDev { get; set; }
    }
}
