//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAssistant
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tester : Employee
    {

        [Display(Name = "Должность тестировщика")]
        [DataType(DataType.Text)]
        public string TesterPosition { get; set; }

        [Display(Name = "Зароботная плата")]
        [DataType(DataType.Currency)]
        public Nullable<double> Salary { get; set; }

        [Display(Name = "Статус")]
        [DataType(DataType.Text)]
        public string Status { get; set; }
    }
}
